version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis-test
    ports:
      - "6379:6379"
    networks:
      - dev-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper-test
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dev-network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-test
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dev-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb-test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dangdang_dev
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
