---
name: '🐞 Bug report'
title: '🐞 [Bug] 제목을 입력해주세요'
labels: ["bug"]
assignees: []
---

## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

## 📖 참고할만한 자료 (선택)

> 참고할 만한 링크나 문서가 있다면 추가해주세요
