---
name: '💡 기능 요청'
title: '💡 [Feature] 제목을 입력해주세요'
labels: ["feature"]
assignees: ["username"]
---

## 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

## 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 📖 참고할만한 자료 (선택)

> 참고할 만한 링크나 문서가 있다면 추가해주세요
